### ISSUE TITLE
Add bio for betnguye

### ISSUE THREAD

**Issue by betnguye** [githubteacher/developers-dec-2015#24]
*[]create a branch
*[]add a bio file for githubstudent
*[]open a pull request
*[]get feedback
*[]merge pull request

**Comment by betnguye** [comment]
* [ ] create a branch

**Comment by betnguye** [comment]
* []create a branch
* []add a bio file for githubstudent
* []open a pull request
* []get feedback
* []merge pull request

**Comment by betnguye** [comment]
* [ ]create a branch
* [ ]add a bio file for githubstudent
* [ ]open a pull request
* [ ]get feedback
* [ ]merge pull request

**Comment by betnguye** [comment]
*[ ]create a branch
    *[ ]add a bio file for githubstudent
    *[ ]open a pull request
    *[ ]get feedback
    *[ ]merge pull request

**Comment by betnguye** [comment]
*[] create a branch
*[] add a bio file for betnguye
*[] open a pull request
*[] get feedback
*[] merge pull request

**Comment by betnguye** [comment]
*[ ] test

**Comment by betnguye** [comment]
*[] test

**Comment by betnguye** [comment]
* []

**Comment by betnguye** [comment]
*[ ]

**Comment by betnguye** [comment]
- [x] create a branch
- [x] add a bio file for betnguye
- [x] open a pull request
- [x] get feedback
- [x] merge pull request

**Comment by dliu001** [comment]
@betnguye maybe could you add your favorite breakfast
