### ISSUE TITLE
Reason for leaving in staging and not committing

### ISSUE THREAD

**Issue by dsc-allenk** [githubteacher/developers-dec-2015#79]
For what reason might one intentionally leave something in staging, but not committed, and go do something else, leaving the local repository in this state?

**Comment by githubteacher** [comment]
It depends on your workflow.  For instance, you might make changes to one file and stage those changes before working on a different file.  This lets you keep track of the changes you have made and ensure those changes are staged.

In most cases, you may find it more helpful to make changes and then stage those changes all at once before committing.
